FROM node:16.13.0-stretch-slim

WORKDIR /workspace/lawtechhackson_client

COPY ./lawtechhackson_client/package.json /workspace/lawtechhackson_client/package.json
COPY ./lawtechhackson_client/yarn.lock /workspace/lawtechhackson_client/yarn.lock
RUN yarn install --frozen-lockfile

COPY lawtechhackson_client/. /workspace/lawtechhackson_client
EXPOSE 3000

CMD ["npm", "run", "start"]
