FROM node:16.13.0-stretch-slim

WORKDIR /workspace
COPY package.json /workspace/package.json
COPY package-lock.json /workspace/package-lock.json
RUN npm ci

COPY . /workspace

EXPOSE 3000

CMD ["npm", "start"]
